//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locutor_da_Hora.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Locutor_da_Hora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locucoes.bin.
        /// </summary>
        public static string Arquivo_Locucoes {
            get {
                return ResourceManager.GetString("Arquivo_Locucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail_template.xml.
        /// </summary>
        public static string Arquivo_TemplateEmail {
            get {
                return ResourceManager.GetString("Arquivo_TemplateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos MP3 | *.MP3.
        /// </summary>
        public static string Dialog_Filter_MP3 {
            get {
                return ResourceManager.GetString("Dialog_Filter_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagens PNG | *.png.
        /// </summary>
        public static string Dialog_Filter_PNG {
            get {
                return ResourceManager.GetString("Dialog_Filter_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo de áudio.
        /// </summary>
        public static string Dialog_SelecionarAudio {
            get {
                return ResourceManager.GetString("Dialog_SelecionarAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo de imagem.
        /// </summary>
        public static string Dialog_SelecionarIcone {
            get {
                return ResourceManager.GetString("Dialog_SelecionarIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo não suportado!.
        /// </summary>
        public static string Exception_ArquivoInvalido {
            get {
                return ResourceManager.GetString("Exception_ArquivoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao enviar e-mail! Verifique se o computador está conectado à internet e as credenciais do servidor estão corretas..
        /// </summary>
        public static string Exception_EnviarEmail {
            get {
                return ResourceManager.GetString("Exception_EnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir o Ícone!.
        /// </summary>
        public static string Exception_ExcluirIcone {
            get {
                return ResourceManager.GetString("Exception_ExcluirIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir a Trilha Sonora!.
        /// </summary>
        public static string Exception_ExcluirTrilha {
            get {
                return ResourceManager.GetString("Exception_ExcluirTrilha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar arquivo, tente novamente..
        /// </summary>
        public static string Exception_ExportarAudio {
            get {
                return ResourceManager.GetString("Exception_ExportarAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao iniciar gravação..
        /// </summary>
        public static string Exception_IniciarGravacao {
            get {
                return ResourceManager.GetString("Exception_IniciarGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao interromper gravação..
        /// </summary>
        public static string Exception_InterromperGravacao {
            get {
                return ResourceManager.GetString("Exception_InterromperGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resolução do seu monitor está muito baixa. Para funcionar corretamente o Locutor da Hora precisa de pelo menos 1024x768px..
        /// </summary>
        public static string Exception_ResolucaoNaoSuportada {
            get {
                return ResourceManager.GetString("Exception_ResolucaoNaoSuportada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar Locuções!.
        /// </summary>
        public static string Exception_SalvarLocucoes {
            get {
                return ResourceManager.GetString("Exception_SalvarLocucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontramos um microfone em seu computador. As funcionalidades de gravação foram desativadas. Conecte um microfone e reinicie o aplicativo..
        /// </summary>
        public static string Exception_SemMicrofone {
            get {
                return ResourceManager.GetString("Exception_SemMicrofone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar Faixa.
        /// </summary>
        public static string Header_MiCarregar {
            get {
                return ResourceManager.GetString("Header_MiCarregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar Trecho.
        /// </summary>
        public static string Header_MiCortar {
            get {
                return ResourceManager.GetString("Header_MiCortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Faixa/Trecho.
        /// </summary>
        public static string Header_MiMesclarEExportar {
            get {
                return ResourceManager.GetString("Header_MiMesclarEExportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Trecho.
        /// </summary>
        public static string Header_MiRemoverTrecho {
            get {
                return ResourceManager.GetString("Header_MiRemoverTrecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desejo receber novidades sobre o projeto..
        /// </summary>
        public static string Label_Checkbox_Newsletter {
            get {
                return ResourceManager.GetString("Label_Checkbox_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDADE.
        /// </summary>
        public static string Label_Usuario_Cidade {
            get {
                return ResourceManager.GetString("Label_Usuario_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        public static string Label_Usuario_Email {
            get {
                return ResourceManager.GetString("Label_Usuario_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        public static string Label_Usuario_Nome {
            get {
                return ResourceManager.GetString("Label_Usuario_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RÁDIO.
        /// </summary>
        public static string Label_Usuario_Radio {
            get {
                return ResourceManager.GetString("Label_Usuario_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string Label_Usuario_UF {
            get {
                return ResourceManager.GetString("Label_Usuario_UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Locução.
        /// </summary>
        public static string Locucao_Adicionar {
            get {
                return ResourceManager.GetString("Locucao_Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locutor da Hora.
        /// </summary>
        public static string NomeAplicacao {
            get {
                return ResourceManager.GetString("NomeAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Gravações.
        /// </summary>
        public static string PastaTemporaria_MP3 {
            get {
                return ResourceManager.GetString("PastaTemporaria_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização Disponível.
        /// </summary>
        public static string Text_BtAtualizar {
            get {
                return ResourceManager.GetString("Text_BtAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliar o Aplicativo.
        /// </summary>
        public static string Text_BtAvaliar {
            get {
                return ResourceManager.GetString("Text_BtAvaliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançar.
        /// </summary>
        public static string Text_BtAvancar {
            get {
                return ResourceManager.GetString("Text_BtAvancar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Text_BtConfiguracoes {
            get {
                return ResourceManager.GetString("Text_BtConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Locuções.
        /// </summary>
        public static string Text_BtEditarLocucoes {
            get {
                return ResourceManager.GetString("Text_BtEditarLocucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Text_BtEnviarEmail {
            get {
                return ResourceManager.GetString("Text_BtEnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar via E-mail.
        /// </summary>
        public static string Text_BtEnviarViaEmail {
            get {
                return ResourceManager.GetString("Text_BtEnviarViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar Novamente.
        /// </summary>
        public static string Text_BtGravarNovamente {
            get {
                return ResourceManager.GetString("Text_BtGravarNovamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string Text_BtIniciar {
            get {
                return ResourceManager.GetString("Text_BtIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Gravação.
        /// </summary>
        public static string Text_BtIniciarGravacao {
            get {
                return ResourceManager.GetString("Text_BtIniciarGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interromper Edição.
        /// </summary>
        public static string Text_BtInterromperEdicao {
            get {
                return ResourceManager.GetString("Text_BtInterromperEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interromper Gravação.
        /// </summary>
        public static string Text_BtInterromperGravacao {
            get {
                return ResourceManager.GetString("Text_BtInterromperGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Áudio.
        /// </summary>
        public static string Text_BtModoEdicao {
            get {
                return ResourceManager.GetString("Text_BtModoEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        public static string Text_BtParar {
            get {
                return ResourceManager.GetString("Text_BtParar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausar.
        /// </summary>
        public static string Text_BtPausar {
            get {
                return ResourceManager.GetString("Text_BtPausar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Ícone.
        /// </summary>
        public static string Text_BtRemoverIcone {
            get {
                return ResourceManager.GetString("Text_BtRemoverIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Trilha Sonora.
        /// </summary>
        public static string Text_BtRemoverTrilhaSonora {
            get {
                return ResourceManager.GetString("Text_BtRemoverTrilhaSonora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduzir.
        /// </summary>
        public static string Text_BtReproduzir {
            get {
                return ResourceManager.GetString("Text_BtReproduzir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Text_BtSair {
            get {
                return ResourceManager.GetString("Text_BtSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Text_BtSalvar {
            get {
                return ResourceManager.GetString("Text_BtSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        public static string Text_BtSelecionarIcone {
            get {
                return ResourceManager.GetString("Text_BtSelecionarIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        public static string Text_BtSelecionarTrilhaSonora {
            get {
                return ResourceManager.GetString("Text_BtSelecionarTrilhaSonora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Text_BtVoltar {
            get {
                return ResourceManager.GetString("Text_BtVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar ao Início.
        /// </summary>
        public static string Text_BtVoltarInicio {
            get {
                return ResourceManager.GetString("Text_BtVoltarInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando.
        /// </summary>
        public static string Text_Carregando {
            get {
                return ResourceManager.GetString("Text_Carregando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Text_FimSelecao {
            get {
                return ResourceManager.GetString("Text_FimSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Text_InicioSelecao {
            get {
                return ResourceManager.GetString("Text_InicioSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção:.
        /// </summary>
        public static string Text_Selecao {
            get {
                return ResourceManager.GetString("Text_Selecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trilha Sonora.
        /// </summary>
        public static string Text_TrilhaSonora {
            get {
                return ResourceManager.GetString("Text_TrilhaSonora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voz.
        /// </summary>
        public static string Text_Voz {
            get {
                return ResourceManager.GetString("Text_Voz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADICIONAR LOCUÇÃO.
        /// </summary>
        public static string Titulo_AdicionarLocucao {
            get {
                return ResourceManager.GetString("Titulo_AdicionarLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR GRAVAÇÃO.
        /// </summary>
        public static string Titulo_EditarGravacao {
            get {
                return ResourceManager.GetString("Titulo_EditarGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR LOCUÇÃO.
        /// </summary>
        public static string Titulo_EditarLocucao {
            get {
                return ResourceManager.GetString("Titulo_EditarLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR E-MAIL.
        /// </summary>
        public static string Titulo_EnviarEmail {
            get {
                return ResourceManager.GetString("Titulo_EnviarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFICAÇÃO.
        /// </summary>
        public static string Titulo_Identificacao {
            get {
                return ResourceManager.GetString("Titulo_Identificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Locução.
        /// </summary>
        public static string Titulo_NovaLocucao {
            get {
                return ResourceManager.GetString("Titulo_NovaLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECIONE UMA LOCUÇÃO.
        /// </summary>
        public static string Titulo_SelecioneLocucao {
            get {
                return ResourceManager.GetString("Titulo_SelecioneLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRILHA SONORA.
        /// </summary>
        public static string Titulo_TrilhaSonora {
            get {
                return ResourceManager.GetString("Titulo_TrilhaSonora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deseja receber mensagens com novidades do projeto Locutor da Hora? (Não se preocupe, não enviaremos spam!).
        /// </summary>
        public static string ToolTip_Assinar_Newsletter {
            get {
                return ResourceManager.GetString("ToolTip_Assinar_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para instalar a versão mais recente do Locutor da Hora.
        /// </summary>
        public static string ToolTip_BtAtualizar {
            get {
                return ResourceManager.GetString("ToolTip_BtAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumentar o tamanho do texto.
        /// </summary>
        public static string ToolTip_BtAumentarTamanhoTexto {
            get {
                return ResourceManager.GetString("ToolTip_BtAumentarTamanhoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajude a melhorar o Locutor da Hora.
        /// </summary>
        public static string ToolTip_BtAvaliar {
            get {
                return ResourceManager.GetString("ToolTip_BtAvaliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuir o tamanho do texto.
        /// </summary>
        public static string ToolTip_BtDiminuirTamanhoTexto {
            get {
                return ResourceManager.GetString("ToolTip_BtDiminuirTamanhoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade onde você mora. Essa é fácil, né?.
        /// </summary>
        public static string ToolTip_Usuario_Cidade {
            get {
                return ResourceManager.GetString("ToolTip_Usuario_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu endereço de e-mail para enviarmos a gravação..
        /// </summary>
        public static string ToolTip_Usuario_Email {
            get {
                return ResourceManager.GetString("ToolTip_Usuario_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como você se chama?.
        /// </summary>
        public static string ToolTip_Usuario_Nome {
            get {
                return ResourceManager.GetString("ToolTip_Usuario_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da rádio que você representa, ou instituição que faz parte, seja como estudante ou profissional..
        /// </summary>
        public static string ToolTip_Usuario_Radio {
            get {
                return ResourceManager.GetString("ToolTip_Usuario_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado onde você mora..
        /// </summary>
        public static string ToolTip_Usuario_UF {
            get {
                return ResourceManager.GetString("ToolTip_Usuario_UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe sua cidade..
        /// </summary>
        public static string Validation_Cidade {
            get {
                return ResourceManager.GetString("Validation_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informando seu e-mail você poderá optar por receber uma mensagem com sua participação no Locutor da Hora! Não se preocupe, não enviaremos spam..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe seu nome..
        /// </summary>
        public static string Validation_Nome {
            get {
                return ResourceManager.GetString("Validation_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a instituição que você faz parte, seja como estudante ou profissional..
        /// </summary>
        public static string Validation_Radio {
            get {
                return ResourceManager.GetString("Validation_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o estado em que você reside..
        /// </summary>
        public static string Validation_UF {
            get {
                return ResourceManager.GetString("Validation_UF", resourceCulture);
            }
        }
    }
}
