//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locutor_da_Hora.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Locutor_da_Hora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locucoes.bin.
        /// </summary>
        public static string Arquivo_Locucoes {
            get {
                return ResourceManager.GetString("Arquivo_Locucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos MP3 | *.MP3.
        /// </summary>
        public static string Dialog_Filter_MP3 {
            get {
                return ResourceManager.GetString("Dialog_Filter_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagens PNG | *.png.
        /// </summary>
        public static string Dialog_Filter_PNG {
            get {
                return ResourceManager.GetString("Dialog_Filter_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo de áudio.
        /// </summary>
        public static string Dialog_SelecionarAudio {
            get {
                return ResourceManager.GetString("Dialog_SelecionarAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo de imagem.
        /// </summary>
        public static string Dialog_SelecionarIcone {
            get {
                return ResourceManager.GetString("Dialog_SelecionarIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo não suportado!.
        /// </summary>
        public static string Exception_ArquivoInvalido {
            get {
                return ResourceManager.GetString("Exception_ArquivoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir o Ícone!.
        /// </summary>
        public static string Exception_ExcluirIcone {
            get {
                return ResourceManager.GetString("Exception_ExcluirIcone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir a Trilha Sonora!.
        /// </summary>
        public static string Exception_ExcluirTrilha {
            get {
                return ResourceManager.GetString("Exception_ExcluirTrilha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar arquivo, tente novamente..
        /// </summary>
        public static string Exception_ExportarAudio {
            get {
                return ResourceManager.GetString("Exception_ExportarAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao iniciar gravação..
        /// </summary>
        public static string Exception_IniciarGravacao {
            get {
                return ResourceManager.GetString("Exception_IniciarGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao interromper gravação..
        /// </summary>
        public static string Exception_InterromperGravacao {
            get {
                return ResourceManager.GetString("Exception_InterromperGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resolução do seu monitor está muito baixa. Para funcionar corretamente o Locutor da Hora precisa de pelo menos 1024x768px..
        /// </summary>
        public static string Exception_ResolucaoNaoSuportada {
            get {
                return ResourceManager.GetString("Exception_ResolucaoNaoSuportada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar Locuções!.
        /// </summary>
        public static string Exception_SalvarLocucoes {
            get {
                return ResourceManager.GetString("Exception_SalvarLocucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontramos um microfone em seu computador. As funcionalidades de gravação foram desativadas. Conecte um microfone e reinicie o aplicativo..
        /// </summary>
        public static string Exception_SemMicrofone {
            get {
                return ResourceManager.GetString("Exception_SemMicrofone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Locução.
        /// </summary>
        public static string Locucao_Adicionar {
            get {
                return ResourceManager.GetString("Locucao_Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locutor da Hora.
        /// </summary>
        public static string NomeAplicacao {
            get {
                return ResourceManager.GetString("NomeAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Gravações.
        /// </summary>
        public static string PastaTemporaria_MP3 {
            get {
                return ResourceManager.GetString("PastaTemporaria_MP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADICIONAR LOCUÇÃO.
        /// </summary>
        public static string Titulo_AdicionarLocucao {
            get {
                return ResourceManager.GetString("Titulo_AdicionarLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR LOCUÇÃO.
        /// </summary>
        public static string Titulo_EditarLocucao {
            get {
                return ResourceManager.GetString("Titulo_EditarLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Locução.
        /// </summary>
        public static string Titulo_NovaLocucao {
            get {
                return ResourceManager.GetString("Titulo_NovaLocucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe sua cidade..
        /// </summary>
        public static string Validation_Cidade {
            get {
                return ResourceManager.GetString("Validation_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informando seu e-mail você poderá optar por receber uma mensagem com sua participação no Locutor da Hora! Não se preocupe, não enviaremos spam..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe seu nome..
        /// </summary>
        public static string Validation_Nome {
            get {
                return ResourceManager.GetString("Validation_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a instituição que você faz parte, seja como estudante ou profissional..
        /// </summary>
        public static string Validation_Radio {
            get {
                return ResourceManager.GetString("Validation_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe o estado em que você reside..
        /// </summary>
        public static string Validation_UF {
            get {
                return ResourceManager.GetString("Validation_UF", resourceCulture);
            }
        }
    }
}
